# Generated by Django 4.1.1 on 2023-06-02 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_date", models.DateField(null=True)),
                ("times", models.JSONField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                (
                    "ap_paterno",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Apellido paterno",
                    ),
                ),
                (
                    "ap_materno",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Apellido materno",
                    ),
                ),
                (
                    "celular",
                    models.CharField(
                        blank=True, default="", max_length=15, verbose_name="Celular"
                    ),
                ),
                (
                    "email_token",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Email token",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Activo"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Date",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hour", models.TimeField()),
                (
                    "service",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Servicio"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "confirm",
                    models.BooleanField(default=False, verbose_name="Confirmar Cita"),
                ),
                (
                    "pacient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.paciente",
                        verbose_name="Paciente",
                    ),
                ),
            ],
        ),
    ]
