# Generated by Django 4.1.7 on 2023-03-19 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='username',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='Servicio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
        ),
    ]
