# Generated by Django 4.1.7 on 2023-03-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_paciente_username_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='Confirmar Cita'),
        ),
    ]
