# Generated by Django 4.1.1 on 2023-06-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_paciente_email_paciente_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="admin"),
        ),
    ]
