# Generated by Django 4.1.7 on 2023-03-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_date_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Numero de mes')),
                ('day', models.IntegerField(verbose_name='Numero de día')),
                ('hour', models.TimeField(verbose_name='Numero de hora')),
            ],
        ),
    ]
