# Generated by Django 4.1.7 on 2023-03-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_availability_hour_availability_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='year',
            field=models.IntegerField(default=2023, verbose_name='Año'),
        ),
    ]
