# Generated by Django 4.1.1 on 2023-03-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_availability_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="email_token",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Email token"
            ),
        ),
    ]
